# Generated by Django 3.2 on 2021-04-21 14:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Album',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Название альбома')),
                ('slug', models.SlugField(unique=True)),
                ('release_date', models.DateField()),
            ],
            options={
                'verbose_name': 'Альбом',
                'verbose_name_plural': 'Альбомы',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Artist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True, verbose_name='Исполнитель')),
                ('birth_date', models.DateField(default=None)),
                ('bio', models.TextField(verbose_name='Описание')),
                ('slug', models.SlugField(unique=True)),
                ('albums', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='sounds.album')),
            ],
            options={
                'verbose_name': 'Исполнитель',
                'verbose_name_plural': 'Исполнители',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True, verbose_name='Жанр')),
                ('description', models.TextField(verbose_name='Описание')),
                ('slug', models.SlugField(unique=True)),
            ],
            options={
                'verbose_name': 'Жанр',
                'verbose_name_plural': 'Жанры',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Playlist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Название плейлиста')),
                ('slug', models.SlugField(unique=True)),
            ],
            options={
                'verbose_name': 'Плейлист',
                'verbose_name_plural': 'Плейлисты',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('photo', models.ImageField(height_field=30, upload_to='avatars/%Y/%m/%d/', width_field=30)),
                ('slug', models.SlugField(unique=True)),
                ('own_playlist', models.ManyToManyField(to='sounds.Playlist')),
            ],
            options={
                'verbose_name': 'Пользователь',
                'verbose_name_plural': 'Пользователи',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Song',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Song')),
                ('image', models.ImageField(height_field=30, upload_to='songs_images/%Y/%m/%d/', width_field=30)),
                ('video', models.URLField(default=None)),
                ('slug', models.SlugField(unique=True)),
                ('is_published', models.BooleanField(default=True)),
                ('album_of_song', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='sounds.album')),
                ('creator', models.ManyToManyField(to='sounds.Artist')),
                ('genres', models.ManyToManyField(to='sounds.Genre')),
            ],
            options={
                'verbose_name': 'Песня',
                'verbose_name_plural': 'Песни',
                'ordering': ['name', 'is_published'],
            },
        ),
        migrations.AddField(
            model_name='playlist',
            name='creator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sounds.user'),
        ),
        migrations.AddField(
            model_name='playlist',
            name='song',
            field=models.ManyToManyField(to='sounds.Song'),
        ),
        migrations.AddField(
            model_name='artist',
            name='song_list',
            field=models.ManyToManyField(to='sounds.Song'),
        ),
        migrations.AddField(
            model_name='album',
            name='creator',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.SET_DEFAULT, to='sounds.artist'),
        ),
        migrations.AddField(
            model_name='album',
            name='songs',
            field=models.ManyToManyField(to='sounds.Song'),
        ),
    ]
