# Generated by Django 3.2 on 2021-04-26 21:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sounds', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='playlist',
            name='creator',
        ),
        migrations.AlterField(
            model_name='artist',
            name='albums',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='sounds.album'),
        ),
        migrations.AlterField(
            model_name='artist',
            name='song_list',
            field=models.ManyToManyField(blank=True, to='sounds.Song'),
        ),
        migrations.AlterField(
            model_name='playlist',
            name='slug',
            field=models.SlugField(unique=True, verbose_name='Слаг'),
        ),
        migrations.AlterField(
            model_name='playlist',
            name='song',
            field=models.ManyToManyField(blank=True, null=True, to='sounds.Song'),
        ),
        migrations.AlterField(
            model_name='song',
            name='image',
            field=models.ImageField(blank=True, height_field=30, upload_to='songs_images/%Y/%m/%d/', width_field=30),
        ),
        migrations.AlterField(
            model_name='user',
            name='own_playlist',
            field=models.ManyToManyField(blank=True, to='sounds.Playlist'),
        ),
        migrations.AlterField(
            model_name='user',
            name='photo',
            field=models.ImageField(blank=True, height_field=30, upload_to='avatars/%Y/%m/%d/', width_field=30),
        ),
    ]
