# Generated by Django 3.2 on 2021-04-27 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sounds', '0002_auto_20210427_0055'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='album',
            name='songs',
        ),
        migrations.RemoveField(
            model_name='artist',
            name='song_list',
        ),
        migrations.AlterField(
            model_name='playlist',
            name='song',
            field=models.ManyToManyField(blank=True, null=True, related_name='playlists', to='sounds.Song'),
        ),
        migrations.AlterField(
            model_name='song',
            name='creator',
            field=models.ManyToManyField(related_name='songs', to='sounds.Artist'),
        ),
        migrations.AlterField(
            model_name='song',
            name='genres',
            field=models.ManyToManyField(related_name='songs', to='sounds.Genre'),
        ),
    ]
